# Updated schema.yaml to match train.csv
columns:
  - name: location_id
    dtype: object
  - name: timestamp
    dtype: object
  - name: precipitation_rate_mm_hr
    dtype: float
  - name: pore_pressure_kpa
    dtype: float
  - name: subsurface_displacement_mm
    dtype: float
  - name: ground_acceleration_g
    dtype: float
  - name: realtime_water_table_m
    dtype: float
  - name: cumulative_precip_72hr
    dtype: float
  - name: cumulative_precip_168hr
    dtype: float
  - name: ucs_mpa
    dtype: float
  - name: seismic_zone
    dtype: object
  - name: pga_g
    dtype: float
  - name: initial_water_table_m
    dtype: float
  - name: rockfall_event
    dtype: int
  - name: 3d_surface_coord_x
    dtype: float
  - name: 3d_surface_coord_y
    dtype: float
  - name: 3d_surface_coord_z
    dtype: float
numerical_columns:
  - precipitation_rate_mm_hr
  - pore_pressure_kpa
  - subsurface_displacement_mm
  - ground_acceleration_g
  - realtime_water_table_m
  - cumulative_precip_72hr
  - cumulative_precip_168hr
  - ucs_mpa
  - pga_g
  - initial_water_table_m
  - 3d_surface_coord_x
  - 3d_surface_coord_y
  - 3d_surface_coord_z
  - rockfall_event
categorical_columns:
  - location_id
  - timestamp
  - seismic_zone
